Added filepath to shipment response
conturo-prototyping/pack-ship-server pull request #161
Opened 2023-07-03 18:48 UTC by joshplumley

2023-07-06 00:59 UTC, jbolles94 requested changes

2023-07-06 00:59 UTC, jbolles94 commented on src/packingSlip/model.js
> +      confirmShipmentFilePath: String,
This should not have changed.

2023-07-06 00:59 UTC, jbolles94 commented on src/shipment/controller.js
> +        itemNoRouter |= item.confirmShipmentFilePath === undefined;
This should not have changed.

2023-07-06 00:59 UTC, jbolles94 commented on src/shipment/controller.js
> +        confirmShipmentFilePath,
If we are changing this, then we need a corresponding FE change.

2023-07-10 00:37 UTC, joshplumley commented
@jbolles94 fixed the names.

2023-07-11 00:24 UTC, jbolles94 approved these changes

2023-07-13 02:05 UTC, jbolles94 approved these changes

2023-07-18 20:18 UTC, merged