Get incoming Delivery Queue
conturo-prototyping/pack-ship-server pull request #58
Opened 2022-09-23 17:27 UTC by mitchell-mccracken

Closes PS-7

Solution: 
* Query all `incomingDeliveries` that do not have a `receivedOn` date.
* Manipulate data to almost the desired format while fetching `WorkOrder` information for each item (as needed).
* Loop through main data set again to populate the `delivery.manifest[idx].item` information to align with required format.

2022-09-26 16:16 UTC, jarrilla requested changes
Working as intended.
Recommend making the suggested changes for scalability

2022-09-26 16:16 UTC, jarrilla commented on src/incomingDelivery/controller.js
> +      for ( const delivery of deliveries ) {
Note: though it won't apply to this, you can also use destructuring to "drop" targetted fields (such as `_id` in some cases).
For example something like `const brr = arr.map( ({ _id, ... }) => ({ ... }) );` would do just that.

2022-09-26 21:22 UTC, mitchell-mccracken commented on src/incomingDelivery/controller.js
> +      for ( const delivery of deliveries ) {
Updated, take a look to see if it was what you had in mind

2022-09-26 21:22 UTC, mitchell-mccracken commented on src/incomingDelivery/controller.js
> +      async function _populateItems(orderNumber) {
fixed

2022-09-26 21:53 UTC, jbolles94 commented
@mitchell-mccracken This seems to be working for at least the basic cases. I am working on integrating it fully into https://github.com/conturo-prototyping/pack-ship-client/pull/90 now and will get more complicated test cases going as I work with it.

2022-09-26 22:37 UTC, jbolles94 commented
@jarrilla and @mitchell-mccracken When filling out the shipping ID column on the FE, I imagine that we want some text there for which shipment it is; however, if I just go with the literal MongoDB ID as is returned by this endpoint, it will just be a string of random chars to the user which I don't think is the behavior that is desired. I believe we want something like `DEF-SH1` as in the shipment history tab, but we currently aren't returning that. Is that something we can add to this endpoint or was there something else in mind?

2022-09-28 01:06 UTC, jarrilla commented
> @jarrilla and @mitchell-mccracken When filling out the shipping ID column on the FE, I imagine that we want some text there for which shipment it is; however, if I just go with the literal MongoDB ID as is returned by this endpoint, it will just be a string of random chars to the user which I don't think is the behavior that is desired. I believe we want something like `DEF-SH1` as in the shipment history tab, but we currently aren't returning that. Is that something we can add to this endpoint or was there something else in mind?

@jbolles94 I changed up the "traditional" schema and made a new field `label` which if we followed previously convention would've been called `incomingDeliveryId` and then it would've been confusing to deal with.

`_id` is the intended mongo document ID and `label` should be the item you're looking for.

2022-09-28 01:09 UTC, jarrilla commented on src/incomingDelivery/controller.js
> +      const data = { ret }
should be
```
const data = {
  incomingDeliveries: ret
};
```
to adhere to required return structure.

2022-09-28 01:12 UTC, jarrilla requested changes
Changes look good. Just one last thing, I think

2022-09-28 01:12 UTC, jarrilla commented on src/incomingDelivery/controller.js
> +      const data = { ret }
should be
```
const data = {
  incomingDeliveries: ret
};
```
to adhere to required return structure.

2022-09-29 00:12 UTC, jbolles94 commented
> > @jarrilla and @mitchell-mccracken When filling out the shipping ID column on the FE, I imagine that we want some text there for which shipment it is; however, if I just go with the literal MongoDB ID as is returned by this endpoint, it will just be a string of random chars to the user which I don't think is the behavior that is desired. I believe we want something like `DEF-SH1` as in the shipment history tab, but we currently aren't returning that. Is that something we can add to this endpoint or was there something else in mind?
> 
> @jbolles94 I changed up the "traditional" schema and made a new field `label` which if we followed previously convention would've been called `incomingDeliveryId` and then it would've been confusing to deal with.
> 
> `_id` is the intended mongo document ID and `label` should be the item you're looking for.

That makes sense to me. Currently, I am not getting a label field returned from this endpoint. Is that something that will come later or should I be seeing it here?

2022-09-29 00:39 UTC, jarrilla commented
If label isn't there that's definitely a problem i missed!

@mitchell-mccracken can you hop on this tomorrow?

2022-09-29 12:40 UTC, mitchell-mccracken commented
Issue is that when creating new Incoming Deliveries the route is not sending the `label` string. Working on the update now.

2022-09-29 14:01 UTC, mitchell-mccracken commented
Updated.

2022-10-03 20:51 UTC, jarrilla approved these changes

2022-10-03 20:51 UTC, jarrilla commented on src/incomingDelivery/controller.js
> +      const query = { receivedOn: { $exists: false } };
Missing `{ isPastVersion: { $ne: true } }`

2022-10-03 20:51 UTC, merged