Delete routesteps mq 6
conturo-prototyping/pack-ship-server pull request #72
Opened 2022-10-04 20:54 UTC by mitchell-mccracken

Closes MQ-6

Solution: 
* Added content to `routeStep/controller.ts` file including `deleteRouteStep` function.
Added `routeStep` path to `app.ts`

2022-10-13 16:52 UTC, jbolles94 requested changes

2022-10-13 16:53 UTC, jbolles94 commented on src/routeStep/controller.ts
> +function deleteRouteStep(
can we add a unit test for this?

2022-10-20 22:01 UTC, jarrilla commented on src/routeStep/controller.ts
> +      if ( !routeStepId ) return HTTPError('no route step id provided');
fixed

2022-10-20 22:07 UTC, jarrilla commented on src/routeStep/controller.ts
> +function deleteRouteStep(
done

2022-10-20 22:07 UTC, jarrilla commented
tests passing; merging

2022-10-20 22:07 UTC, merged